name: Build TI-84 CE Program

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up CE Toolchain
        uses: CE-Programming/toolchain-action@v1

      - name: Compile Program
        run: make

      - name: Upload .8xp File
        uses: actions/upload-artifact@v4
        with:
          name: VIDPLAYER-8xp
          path: bin/VIDPLAYER.8xp
